# Generated by Django 5.2.17 on 2026-09-22 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('stars', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
